name: anniet2020
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.9.2


#==========================================#
dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8

  smooth_page_indicator:
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.2
  shared_preferences: ^2.5.3
  http: ^1.5.0
  device_preview:
  flutter_easyloading:
  pin_code_fields: ^8.0.1
  image_picker: ^1.2.1
  mime: ^2.0.0
  url_launcher:
  video_player: ^2.10.1
  chewie:
  http_parser: ^4.0.2
  pdf: ^3.11.3
  printing: ^5.14.2
  open_file: ^3.5.10
  path_provider: ^2.1.5
  permission_handler:



#==========================================#
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0


#==========================================#
flutter:
  
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
